# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b567a9cfd7863359c190ffb08d05bcb6128470a6878ffa10ccf8541c22687ba9d3c97122734cd3945d8198d56a60ad1b731f7387a5b044911b21e03d3046c39a

test:
  secret_key_base: 3de527a56a6ae11ec3e2a96b6eb1789ea69ccafe9f2368961513a897370c937072a23affef9d8b0f13572408b6cacef5af1b64e88a76d79159e64d4b0075dc89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
